[tool.poetry]
name = "fossology"
version = "1.3.4"
description = "A library to automate Fossology from Python scripts"
authors = ["Marion Deveaud <marion.deveaud@siemens.com>"]
license = "MIT License"
readme = "README.rst"
include = ["LICENSE.md"]
repository = "https://github.com/fossology/fossology-python"
homepage = "https://github.com/fossology/fossology-python"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
]

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
python = "^3.6"
requests = ">=2.22.0"
tenacity = ">=6.0.0"
click = "^8.0.1"

[tool.poetry.dev-dependencies]
flake8 = ">=3.7.8"
sphinx = ">=2.2.0"
black = "^19.10b0"
coverage = "^5.1"
codecov = "^2.0.22"
pyflakes = "^2.2.0"
pytest = "^5.4.3"
responses = "^0.10.15"
isort = "^5.7.0"

[tool.poetry.scripts]
foss_cli = "fossology.foss_cli:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

